### ISSUE TITLE
Request error: Error when getting stamina info

### ISSUE THREAD

**Issue by fenchai23** [torikushiii/starrail-auto#8]
instead of stopping the script when there is a connection error, why not keep it running?

```
file:///C:/Users/ferna/Desktop/programming/js/starrail-auto/lib/apps/stamina.js:95
                                throw new Error({
                                      ^

CustomError: Error when getting stamina info
- args: {"statusCode":500,"body":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>500 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size=\"1px\">\nThe Lambda@Edge service is currently experiencing problems.\nWe can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR clear=\"all\">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n<BR clear=\"all\">\n<HR noshade size=\"1px\">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: OO3WngBLDQnol-i9D-ZpSG6Kxe3bAQ-_qkziAiZHs-AhEXnlOeYogw==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>"}
    at Stamina.run (file:///C:/Users/ferna/Desktop/programming/js/starrail-auto/lib/apps/stamina.js:95:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CJ.<anonymous> (file:///C:/Users/ferna/Desktop/programming/js/starrail-auto/index.js:49:19) {
  [cause]: undefined
}
```

**Comment by torikushiii** [comment]
I'm currently working on re-building the requests and should be ready soon

**Comment by torikushiii** [comment]
I've completed how the Errors should be handled and now it should not stopped when some account are failed to check.
